# Generated by Django 5.2.4 on 2025-09-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptnName', models.CharField(max_length=100)),
                ('ptnLastname', models.CharField(max_length=100)),
                ('ptnDOB', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='patient_thumbs/')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_patients', to=settings.AUTH_USER_MODEL)),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_models/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='patient_models/thumbs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to=settings.AUTH_USER_MODEL)),
                ('ptnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to='SmileHealth.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgDesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='patient_images/')),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
                ('ptnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='SmileHealth.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_comments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SmileHealth.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(default='https://i.pravatar.cc/150?img=1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidDesc', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ptnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='SmileHealth.patient')),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
