# Generated by Django 5.2.4 on 2025-07-31 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptnName', models.CharField(max_length=100)),
                ('ptnLastname', models.CharField(max_length=100)),
                ('ptnDOB', models.DateField()),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgDesc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='patient_images/')),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
                ('ptnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='SmileHealth.patient')),
            ],
        ),
    ]
