# Generated by Django 5.2.4 on 2025-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Privat'), ('SHARED', 'Geteilt (ausgewählte Nutzer)'), ('PUBLIC_ORG', 'Öffentlich (Organisation)')], db_index=True, default='PRIVATE', max_length=20),
        ),
    ]
