# Generated by Django 5.2.4 on 2025-08-12 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidDesc', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ptnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='SmileHealth.patient')),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
