# Generated by Django 5.2.4 on 2025-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0002_patient_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('DOCTOR', 'Doctor'), ('ASSISTANT', 'Assistant'), ('VIEWER', 'Viewer')], db_index=True, default='VIEWER', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='users', to='SmileHealth.branch'),
        ),
    ]
