# Generated by Django 5.2.4 on 2025-08-12 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0003_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
