# Generated by Django 5.2.4 on 2025-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0003_branch_profile_role_profile_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Privat'), ('SHARED', 'Geteilt (ausgewählte Nutzer)'), ('PUBLIC_ORG', 'Öffentlich (Organisation)')], db_index=True, default='PUBLIC_ORG', max_length=20),
        ),
    ]
