# Generated by Django 5.2.4 on 2026-02-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0004_alter_patient_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Unspecified')], db_index=True, default='UNSPECIFIED', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('USER_CREATED', 'User created'), ('PATIENT_CREATED', 'Patient created'), ('PATIENT_DELETED', 'Patient deleted'), ('PATIENT_SHARED', 'Patient shared'), ('IMAGE_UPLOADED', 'Image uploaded'), ('IMAGE_DELETED', 'Image deleted'), ('VIDEO_UPLOADED', 'Video uploaded'), ('VIDEO_DELETED', 'Video deleted'), ('MODEL3D_UPLOADED', '3D model uploaded'), ('MODEL3D_DELETED', '3D model deleted'), ('COMMENT_ADDED', 'Comment added'), ('MESSAGE_SENT', 'Message sent')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
