# Generated by Django 5.2.4 on 2025-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0004_patient_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='patient_thumbs/'),
        ),
    ]
