# Generated by Django 5.2.4 on 2026-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0005_profile_description_profile_gender_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
