# Generated by Django 5.2.4 on 2026-02-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0006_casegroup_patient_group'),
        ('SmileHealth', '0006_message_is_read'),
    ]

    operations = [
    ]
