# Generated by Django 5.2.4 on 2025-08-22 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmileHealth', '0006_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_models/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='patient_models/thumbs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ptnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to='SmileHealth.patient')),
                ('usrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
